// <auto-generated />
using System;
using BehaviorTest.EntityFramework.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BehaviorTest.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20251009082328_v1.0.1")]
    partial class v101
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Evaluation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("ContentRationalePath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("content_rationale_path");

                    b.Property<decimal?>("ContentScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("content_score");

                    b.Property<string>("EffectRationalePath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("effect_rationale_path");

                    b.Property<decimal?>("EffectScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("effect_score");

                    b.Property<string>("EvaluationModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("evaluation_model");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputSource")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("input_source");

                    b.Property<string>("PhilosophyRationalePath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("philosophy_rationale_path");

                    b.Property<decimal?>("PhilosophyScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("philosophy_score");

                    b.Property<string>("ProcessRationalePath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("process_rationale_path");

                    b.Property<decimal?>("ProcessScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("process_score");

                    b.Property<string>("RawResponseStorePath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("raw_response_store_path");

                    b.Property<string>("ReportStorePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("report_store_path");

                    b.Property<string>("RunUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("run_uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_score");

                    b.Property<ulong>("VideoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("evaluations");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.PipelineRun", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("RunUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("run_uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<ulong>("VideoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("pipeline_runs");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Summary", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<uint?>("CharactersCount")
                        .HasColumnType("int unsigned")
                        .HasColumnName("characters_count");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<ulong?>("RelatedTranscriptId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("related_transcript_id");

                    b.Property<string>("RunUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("run_uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("source");

                    b.Property<string>("SummaryModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("summary_model");

                    b.Property<string>("SummaryStorePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("summary_store_path");

                    b.Property<ulong>("VideoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("RelatedTranscriptId");

                    b.HasIndex("VideoId");

                    b.ToTable("summaries");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Transcript", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<uint?>("CharactersCount")
                        .HasColumnType("int unsigned")
                        .HasColumnName("characters_count");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("language_code");

                    b.Property<string>("RunUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("run_uuid");

                    b.Property<uint>("SegmentIndex")
                        .HasColumnType("int unsigned")
                        .HasColumnName("segment_index");

                    b.Property<string>("TextStorePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("text_store_path");

                    b.Property<string>("TranscriberModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("transcriber_model");

                    b.Property<ulong>("VideoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("transcripts");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 9, 8, 23, 28, 202, DateTimeKind.Utc).AddTicks(7155),
                            Email = "363108445@qq.com",
                            IsDeleted = false,
                            Name = "张三",
                            Password = "fEqNCco3Yq9h5ZUglD3CZJT4lBs=",
                            Role = "admin",
                            UpdatedAt = new DateTime(2025, 10, 9, 8, 23, 28, 202, DateTimeKind.Utc).AddTicks(7160)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 9, 8, 23, 28, 205, DateTimeKind.Utc).AddTicks(8441),
                            Email = "555108445@qq.com",
                            IsDeleted = false,
                            Name = "李四",
                            Password = "fEqNCco3Yq9h5ZUglD3CZJT4lBs=",
                            Role = "operator",
                            UpdatedAt = new DateTime(2025, 10, 9, 8, 23, 28, 205, DateTimeKind.Utc).AddTicks(8445)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 9, 8, 23, 28, 205, DateTimeKind.Utc).AddTicks(8682),
                            Email = "551238445@qq.com",
                            IsDeleted = false,
                            Name = "王五",
                            Password = "fEqNCco3Yq9h5ZUglD3CZJT4lBs=",
                            Role = "viewer",
                            UpdatedAt = new DateTime(2025, 10, 9, 8, 23, 28, 205, DateTimeKind.Utc).AddTicks(8682)
                        });
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Video", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<uint?>("DurationSeconds")
                        .HasColumnType("int unsigned")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_name");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("source_path");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("videos");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Evaluation", b =>
                {
                    b.HasOne("BehaviorTest.Application.RBAC.Entity.Video", "Video")
                        .WithMany("Evaluations")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.PipelineRun", b =>
                {
                    b.HasOne("BehaviorTest.Application.RBAC.Entity.Video", "Video")
                        .WithMany("PipelineRuns")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Summary", b =>
                {
                    b.HasOne("BehaviorTest.Application.RBAC.Entity.Transcript", "RelatedTranscript")
                        .WithMany("Summaries")
                        .HasForeignKey("RelatedTranscriptId");

                    b.HasOne("BehaviorTest.Application.RBAC.Entity.Video", "Video")
                        .WithMany("Summaries")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedTranscript");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Transcript", b =>
                {
                    b.HasOne("BehaviorTest.Application.RBAC.Entity.Video", "Video")
                        .WithMany("Transcripts")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Video", b =>
                {
                    b.HasOne("BehaviorTest.Application.RBAC.Entity.UserEntity", "User")
                        .WithMany("Videos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Transcript", b =>
                {
                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.UserEntity", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.Video", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("PipelineRuns");

                    b.Navigation("Summaries");

                    b.Navigation("Transcripts");
                });
#pragma warning restore 612, 618
        }
    }
}
