// <auto-generated />
using System;
using BehaviorTest.EntityFramework.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BehaviorTest.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20251009030722_v1.0.0")]
    partial class v100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BehaviorTest.Application.RBAC.Entity.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 9, 3, 7, 22, 99, DateTimeKind.Utc).AddTicks(1030),
                            Email = "363108445@qq.com",
                            IsDeleted = false,
                            Name = "张三",
                            Password = "fEqNCco3Yq9h5ZUglD3CZJT4lBs=",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 10, 9, 3, 7, 22, 99, DateTimeKind.Utc).AddTicks(1034)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 9, 3, 7, 22, 283, DateTimeKind.Utc).AddTicks(8865),
                            Email = "555108445@qq.com",
                            IsDeleted = false,
                            Name = "李四",
                            Password = "fEqNCco3Yq9h5ZUglD3CZJT4lBs=",
                            Role = "Teacher",
                            UpdatedAt = new DateTime(2025, 10, 9, 3, 7, 22, 283, DateTimeKind.Utc).AddTicks(8870)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 9, 3, 7, 22, 283, DateTimeKind.Utc).AddTicks(9136),
                            Email = "551238445@qq.com",
                            IsDeleted = false,
                            Name = "王五",
                            Password = "fEqNCco3Yq9h5ZUglD3CZJT4lBs=",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 10, 9, 3, 7, 22, 283, DateTimeKind.Utc).AddTicks(9136)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
